version: "3.3"
services:
  postgresdb:
    container_name: spdxyz-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "54321:5432"
  redis:
    container_name: spdxyz-redis
    image: redis
    ports:
      - "63791:6379"
  rabbitmq:
    container_name: spdxyz-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
